version: "3.9"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
    ports:
      - '5432:5432'
  nsqlookupd:
    image: nsqio/nsq
    entrypoint: /nsqlookupd
    ports:
      - "4160:4160"
      - "4161:4161"
  nsqd:
    image: nsqio/nsq
    entrypoint: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - "4150:4150"
      - "4151:4151"
  nsqadmin:
    image: nsqio/nsq
    entrypoint: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd
    ports:
      - "4171:4171"
  jobs-watcher:
    build:
      context: .
      dockerfile: cmd/jobs-watcher/Dockerfile
    restart: always
    entrypoint: '/watcher -q nsqd:4150 -j "host=postgres port=5432 user=postgres password=postgres dbname=postgres sslmode=disable"'
    depends_on:
      - postgres
      - nsqd
  jobs-creator:
    environment:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
    build:
      context: .
      dockerfile: cmd/jobs-creator/Dockerfile
    restart: always
    entrypoint: '/creator -n https://mainnet.infura.io/v3/d7b15235a515483490a5b89644221a71 -w wss://mainnet.infura.io/ws/v3/d7b15235a515483490a5b89644221a71 -j "host=postgres port=5432 user=postgres password=postgres dbname=postgres sslmode=disable" -g "host=postgres port=5432 user=postgres password=postgres dbname=postgres sslmode=disable"'
    depends_on:
      - postgres
  parsing-dispatcher:
    environment:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
    build:
      context: .
      dockerfile: cmd/parsing-dispatcher/Dockerfile
    restart: always
    entrypoint: '/dispatcher -k nsqlookupd:4161 -j "host=postgres port=5432 user=postgres password=postgres dbname=postgres sslmode=disable" -e "host=postgres port=5432 user=postgres password=postgres dbname=postgres sslmode=disable"'
    depends_on:
      - postgres
      - nsqlookupd
  addition-dispatcher:
    environment:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
    build:
      context: .
      dockerfile: cmd/addition-dispatcher/Dockerfile
    restart: always
    entrypoint: '/dispatcher -k nsqlookupd:4161 -j "host=postgres port=5432 user=postgres password=postgres dbname=postgres sslmode=disable" -g "host=postgres port=5432 user=postgres password=postgres dbname=postgres sslmode=disable"'
    depends_on:
      - postgres
      - nsqlookupd
