version: "3.9"
services:
  watcher:
    build:
      context: .
      dockerfile: Dockerfile_watcher
    entrypoint: "/watcher wss://mainnet.infura.io/ws/v3/d7b15235a515483490a5b89644221a71 web3 -u redis:6379"
    depends_on:
      - redis
  dispatcher_agent:
    build:
      context: .
      dockerfile: Dockerfile_discovery_agent
    entrypoint: "/agent -u redis:6379 -t -f http://127.0.0.1:3001"
    depends_on:
      - redis
  api:
    build:
      context: .
      dockerfile: Dockerfile_api
    entrypoint: "/api -u redis:6379"
    ports:
      - '8081:8081'
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - '6379:6379'
