version: "3.9"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
    ports:
      - '5432:5432'
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
  redis:
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    restart: always
    entrypoint: '/api -d "host=postgres port=5432 user=postgres password=postgres dbname=jobs sslmode=disable"'
    ports:
      - '8081:8081'
    depends_on:
      - postgres
  jobs-watcher:
    build:
      context: .
      dockerfile: Dockerfile.jobwatcher
    restart: always
    entrypoint: '/watcher -a api:8081 -u redis:6379 -d "host=postgres port=5432 user=postgres password=postgres dbname=jobs sslmode=disable"'
    depends_on:
      - api
      - redis
  chain-watcher:
    build:
      context: .
      dockerfile: Dockerfile.chainwatcher
    restart: always
    entrypoint: '/watcher -a api:8081 -u wss://mainnet.infura.io/ws/v3/d7b15235a515483490a5b89644221a71 -i 1 -t web3 -d "host=postgres port=5432 user=postgres password=postgres dbname=chains sslmode=disable"'
    depends_on:
      - api
      - jobs-watcher
  parsing-dispatcher:
    environment:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
    build:
      context: .
      dockerfile: Dockerfile.parsingdispatcher
    restart: always
    entrypoint: '/dispatcher -u redis:6379 -a api:8081 -d "host=postgres port=5432 user=postgres password=postgres dbname=chains sslmode=disable" -e "host=postgres port=5432 user=postgres password=postgres dbname=chains sslmode=disable"'
    depends_on:
      - postgres
      - api
      - redis
  action-dispatcher:
    environment:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
    build:
      context: .
      dockerfile: Dockerfile.actiondispatcher
    restart: always
    entrypoint: '/dispatcher -u redis:6379 -a api:8081 -d "host=postgres port=5432 user=postgres password=postgres dbname=chains sslmode=disable"'
    depends_on:
      - postgres
      - api
      - redis
