version: "3.9"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
    ports:
      - '5432:5432'
  redis:
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
  jobs-watcher:
    build:
      context: .
      dockerfile: cmd/jobs-watcher/Dockerfile
    restart: always
    entrypoint: '/watcher -u redis:6379 -d "host=postgres port=5432 user=postgres password=postgres dbname=postgres sslmode=disable"'
    depends_on:
      - postgres
      - redis
  jobs-creator:
    build:
      context: .
      dockerfile: cmd/jobs-creator/Dockerfile
    restart: always
    entrypoint: '/creator -n wss://mainnet.infura.io/ws/v3/d7b15235a515483490a5b89644221a71 -j "host=postgres port=5432 user=postgres password=postgres dbname=postgres sslmode=disable" -g "host=postgres port=5432 user=postgres password=postgres dbname=postgres sslmode=disable"'
    depends_on:
      - postgres
  parsing-dispatcher:
    environment:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
    build:
      context: .
      dockerfile: cmd/parsing-dispatcher/Dockerfile
    restart: always
    entrypoint: '/dispatcher -u redis:6379 -j "host=postgres port=5432 user=postgres password=postgres dbname=postgres sslmode=disable" -g "host=postgres port=5432 user=postgres password=postgres dbname=postgres sslmode=disable"'
    depends_on:
      - postgres
      - redis
  action-dispatcher:
    environment:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
    build:
      context: .
      dockerfile: cmd/action-dispatcher/Dockerfile
    restart: always
    entrypoint: '/dispatcher -u redis:6379 -j "host=postgres port=5432 user=postgres password=postgres dbname=postgres sslmode=disable" -g "host=postgres port=5432 user=postgres password=postgres dbname=postgres sslmode=disable"'
    depends_on:
      - postgres
      - redis
