version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - /home/ricardo/.docker/nft-com/postgres:/var/lib/postgresql/data