version: "3.9"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
    ports:
      - '5432:5432'
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
  redis:
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
  jobs-api:
    build:
      context: .
      target: jobs-api
    restart: always
    entrypoint: '/jobs-api -d "host=postgres port=5432 user=postgres password=postgres dbname=jobs sslmode=disable"'
    ports:
      - '8081:8081'
    depends_on:
      - postgres
  jobs-watcher:
    build:
      context: .
      target: jobs-watcher
    restart: always
    entrypoint: '/jobs-watcher -a jobs-api:8081 -u redis:6379'
    depends_on:
      - jobs-api
      - redis
  chain-watcher:
    build:
      context: .
      target: chain-watcher
    restart: always
    entrypoint: '/chain-watcher -a jobs-api:8081 -u wss://mainnet.infura.io/ws/v3/d7b15235a515483490a5b89644221a71 -i 1 -t web3 -c 0x4a537f61ef574153664c0dbc8c8f4b900cacbe5d -e 0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef --standard-type ERC721'
    depends_on:
      - jobs-api
      - jobs-watcher
  chain-bootstrapper:
    build:
      context: .
      target: chain-bootstrapper
    entrypoint: '/chain-bootstrapper -a jobs-api:8081 -u wss://mainnet.infura.io/ws/v3/d7b15235a515483490a5b89644221a71 -i 1 -t web3 -c 0xb55b7e00152d2ef27357944a96f29271f8073f11 --event 0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef --standard-type ERC721 -s 1 -e 14398902'
    depends_on:
      - jobs-api
      - jobs-watcher
