FROM golang:1.16-buster AS build
WORKDIR /app
COPY go.mod ./
COPY go.sum ./
RUN go mod download
COPY . .
RUN go build -o /bootstrapper ./cmd/chain-bootstrapper

FROM gcr.io/distroless/base-debian10
WORKDIR /
COPY --from=build /bootstrapper /bootstrapper
USER nonroot:nonroot
ENTRYPOINT ["/bootstrapper"]
