version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "Postgres2022!"
    ports:
      - "15432:5432"
    volumes:
      - /home/ricardo/.docker/nft-com/postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@nft.com"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2022!"
    ports:
      - "16543:80"
    depends_on:
      - postgres