version: "3.9"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
    ports:
      - '5432:5432'
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
  redis:
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    restart: always
    entrypoint: '/api -d "host=75.119.158.206 port=5432 user=postgres password=postgres dbname=jobs sslmode=disable"'
    ports:
      - '8081:8081'
    depends_on:
      - postgres
  watcher:
    build:
      context: .
      dockerfile: Dockerfile.watcher
    restart: always
    entrypoint: '/watcher -a http://api:8081 -u redis:6379'
    depends_on:
      - api
      - redis
  parsing-agent:
    build:
      context: .
      dockerfile: Dockerfile_parsingdispatcher
    restart: always
    entrypoint: '/agent -u redis:6379 -a api:8081'
    depends_on:
      - redis
