name: NFT.com Indexer github actions
on: [push]
jobs:
  deploy-dev:
    if: ${{ startsWith(github.ref_name, 'feat') || startsWith(github.ref_name, 'fix') }}
    runs-on: ubuntu-20.04
    environment: nftcom_indexer_dev
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/deploy-env
        name: Deploy env
        with:
          secrets: ${{ toJSON(secrets) }}
          stage: dev
  deploy-staging:
    if: ${{ github.ref_name == 'main' }}
    runs-on: ubuntu-20.04
    environment: nftcom_indexer_staging
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/deploy-env
        with:
          secrets: ${{ toJSON(secrets) }}
          stage: staging
  deploy-prod:
    if: ${{ github.ref_type == 'tag' && startsWith(github.ref_name, 'rel') }}
    runs-on: ubuntu-20.04
    environment: nftcom_indexer_prod
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/deploy-env
        with:
          secrets: ${{ toJSON(secrets) }}
          stage: prod
